---
- name: Install "nginx" to latest version
  ansible.builtin.apt:
    name: nginx
    state: latest

- name: configure reverse proxy for port 80 access
  ansible.builtin.blockinfile:
    path: /etc/nginx/nginx.conf
    block: |
      events{}

      http {

          server {
            listen 80;
            server_name 18.168.149.157;

            location / {
                proxy_pass http://127.0.0.1:5000;
            }
          }
      }
